# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'National Geographic POD' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for National Geographic POD
  pod ‘Alamofire’
  pod 'SwiftyJSON'
  pod 'Kingfisher'
end

target 'NGPODExtension' do
  use_frameworks!

  # Pods for National Geographic POD
  pod ‘Alamofire’
  pod 'SwiftyJSON'
  pod 'Kingfisher'
end
